### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by sweethuman** [bnwebdev/graphql-collector#12]
This is by far the best solution there is out there to help us optimise the queries in the resolver.
As much as there is stuff like `@ResolveField` in NestJS and other stuff in other frameworks, those aren't good enough since they create a separate resolver.

This is such an elegant solution to collect the necessary fields so we can optimise the database queries in a single resolver. Again, THANK YOU!

**Comment by bnwebdev** [comment]
@sweethuman Thanks a lot for the feedback! I am very glad to hear that my solution managed to help and do their mission!)
